// Lyhyet faktat Haagan kaduista — nimistön teemat ja alueen historia.
window.HAAGA_FACTS = {
"Kauppalantie": "Haaga oli oma kauppala vuosina 1923–1946, kunnes se liitettiin Helsinkiin. Kadun nimi muistaa tämän itsenäisen kauppalakauden.",
"Kylätie": "Vanhan Haagan raittimainen katu: nimi viittaa kauppalan aikaiseen kyläkeskustaan Vanhan viertotien varrella.",
"Vanha viertotie": "\"Viertotie\" oli 1800-luvun nimitys kivetylle maantielle. Tämä katu on osa vanhaa Turkuun johtanutta päätietä, jonka varteen Haaga rakentui.",
"Vanha Turun maantie": "Historiallinen Turun maantie kulki Haagan halki jo kauan ennen kaupunginosaa. Nimi on säilynyt katuna nykyisen liikenteen rinnalla.",
"Eliel Saarisen tie": "Arkkitehti Eliel Saarinen laati vuonna 1915 Munkkiniemi–Haaga-suunnitelman, kunnianhimoisen ja lopulta vain osin toteutuneen kaupunkivision.",
"Loja Saarisen polku": "Loja Saarinen oli tekstiilitaiteilija ja Eliel Saarisen puoliso — nimi täydentää naapurikadun arkkitehtiviittauksen.",
"Steniuksentie": "M. G. Steniuksen yhtiö osti ja palstoitti Haagan maita 1900-luvun alussa ja synnytti huvila-alueen, josta nykyinen Etelä-Haaga kasvoi.",
"Isonnevantie": "Nimi kertoo maastosta: Isoneva oli laaja suoalue, joka kuivatettiin rakentamisen tieltä.",
"Laajasuontie": "Toinen suomuisto Haagan nimistössä — Laajasuo oli alueen kostea, rakentamiseen raivattu maasto.",
"Haagan pappilantie": "Katu kulkee Haagan vanhan pappilan tuntumassa; seurakuntahistoria näkyy nimistössä edelleen.",
"Yhteiskouluntie": "Nimi juontuu Haagan yhteiskoulusta, kauppala-ajan tärkeimmästä oppilaitoksesta.",
"Orapihlajatie": "Etelä-Haagan puutarhakaupunkihenkeä: korttelien katuja nimettiin pensaiden ja puutarhakasvien mukaan.",
"Paatsamatie": "Paatsama on kotimainen pensas — yksi Etelä-Haagan kasviaiheisista kadunnimistä.",
"Seljatie": "Selja eli pihlajaa muistuttava koristepensas kuuluu Etelä-Haagan puutarhanimien sarjaan.",
"Angervotie": "Angervo on suosittu pihapensas; nimi istuu huvila-alueen puutarhateemaan.",
"Kuusamakuja": "Kuusama on köynnöspensas — jatkaa Etelä-Haagan kasvinimien perinnettä.",
"Ruusutarhantie": "Nimi kuvaa huvila-Haagan ideaalia: omakotitalo, hedelmäpuita ja ruusutarha.",
"Ryytimaantie": "Ryytimaa tarkoittaa yrtti- ja kasvitarhaa — muisto ajasta, jolloin tonteilla kasvatettiin ruokaa.",
"Korppaantie": "Nimi tulee Korppaanmäestä, Haagan ja Ruskeasuon välisestä vanhasta mäennimestä.",
"Huopalahdentie": "Katu johti alun perin kohti Huopalahtea, joka oli oma kunta ennen liitoksia Helsinkiin.",
"Vihdintie": "Vanha Vihtiin johtava maantie ja yhä Haagan läntinen pääväylä.",
"Lapinmäentie": "Nimi juontuu Lapinmäestä; katu yhdistää Haagan Munkkivuoren suuntaan.",
"Metsäläntie": "Katu johtaa Metsälän suuntaan, Haagan ja Pasilan välisiin teollisuus- ja asuinkortteleihin.",
"Nuijamiestentie": "Pohjois-Haagan nimistö muistaa nuijasodan 1596–97: nuijamiehet olivat kapinaan nousseita talonpoikia.",
"Ilkantie": "Jaakko Ilkka oli nuijasodan tunnetuin talonpoikaisjohtaja — katu on alueen nuijasota-teeman keskus.",
"Santavuorentie": "Santavuoren taistelu Ilmajoella vuonna 1597 päätti nuijasodan verisesti; nimi jatkaa Pohjois-Haagan teemaa.",
"Huovitie": "Huovit olivat Klaus Flemingin raskaita ratsumiehiä, nuijamiesten vastustajia nuijasodassa.",
"Poutuntie": "Nuijasota-aiheinen nimi kuten naapurikadut; Pohjois-Haagan katunimet kertovat 1500-luvun kapinasta.",
"Krankantie": "Yksi Pohjois-Haagan nuijasotaan viittaavista kadunnimistä.",
"Tolarintie": "Nimi liittyy Pohjois-Haagan 1500-luvun aiheiseen nimistöön.",
"Näyttelijäntie": "Pohjois-Haagassa on oma teatterikorttelinsa: kadut on nimetty näyttelijöiden ja teatterintekijöiden mukaan.",
"Ohjaajantie": "Näyttelijäntien naapuri — teatteriteema jatkuu ohjaajasta lavastajaan.",
"Lavastajanpolku": "Polku täydentää teatteriammattien sarjan Pohjois-Haagassa.",
"Thalianaukio": "Thalia oli komedian muusa antiikin Kreikassa — aukio on teatteriteeman ydin.",
"Adolf Lindforsin tie": "Adolf Lindfors oli Kansallisteatterin näyttelijä ja ohjaaja; hänen mukaansa nimetty katu kuuluu Haagan teatterikortteliin.",
"Aino Acktén tie": "Aino Ackté oli Suomen kansainvälisesti tunnetuin oopperalaulaja ja Savonlinnan oopperajuhlien perustaja.",
"Ida Aalbergin tie": "Ida Aalberg nousi 1800-luvun lopulla Suomen ensimmäiseksi näyttelijätähdeksi ja esiintyi myös ulkomailla.",
"Ida Ekmanin tie": "Laulaja Ida Ekman tunnettiin erityisesti Sibeliuksen laulujen tulkkina.",
"Aku Korhosen tie": "Aku Korhonen oli rakastettu teatteri- ja elokuvanäyttelijä, suomalaisen kansannäyttelijän perikuva.",
"Teuvo Pakkalan tie": "Kirjailija Teuvo Pakkala kuvasi Oulun jokivarren työväkeä; myös kirjailijat pääsivät Haagan nimistöön.",
"Maiju Lassilan tie": "Maiju Lassila oli Algot Untolan kirjailijanimi — \"Tulitikkuja lainaamassa\" on hänen tunnetuin teoksensa.",
"Maria Jotunin tie": "Maria Jotuni oli novellisti ja näytelmäkirjailija, tarkka ihmissuhteiden kuvaaja.",
"Walentin Chorellin tie": "Walentin Chorell oli suomenruotsalainen kirjailija ja näytelmäkirjailija.",
"Pietari Hannikaisen tie": "Pietari Hannikainen oli kirjailija ja sanomalehtimies, suomenkielisen kulttuurin varhainen edistäjä.",
"Kivihaantie": "Kivihaan pääkatu. Nimi tulee kivisestä hakamaasta — alue rakennettiin 1950-luvulla metsäiseen rinteeseen.",
"Matkamiehentie": "Nimi muistaa vanhan Turun maantien kulkijoita: matkamiehiä, jotka taittoivat taivalta Haagan kautta.",
"Hopeatie": "Lassilan kadut on nimetty vanhojen rahojen ja painomittojen mukaan — hopea aloittaa sarjan.",
"Kuparitie": "Kuparirahat olivat arkista pikkurahaa; Lassilan nimistö on kokonainen vanhan rahan ja mittojen näyttely.",
"Pronssitie": "Jatkaa Lassilan metallien sarjaa hopean ja kuparin rinnalla.",
"Tinatie": "Tina kuuluu Lassilan metalliaiheisiin kadunnimiin.",
"Puntaritie": "Puntari on vanha vipuvaaka — Lassilassa myös punnitusvälineet pääsivät kadunnimiin.",
"Vaakatie": "Vaaka jatkaa Lassilan mitta- ja punnitusteemaa.",
"Leiviskätie": "Leiviskä oli vanha painomitta, noin 8,5 kiloa.",
"Sentnerikuja": "Sentneri eli sentneripaino oli vanha, noin 42 kilon painomitta.",
"Naulapolku": "Naula oli vanha painoyksikkö, noin 425 grammaa — ei siis kiinnitystarvike.",
"Killinkipolku": "Killinki oli vanha hopearaha; Lassilan poluilla kulkee kokonainen rahahistoria.",
"Äyripolku": "Äyri oli keskiaikainen rahayksikkö ja myöhemmin veroäyri.",
"Taalaripolku": "Taaleri oli Ruotsin vallan aikainen suuri hopearaha.",
"Pennikuja": "Penni oli Suomen markan sadasosa vuoteen 2002 asti.",
"Kippuntapolku": "Kippunta oli suurin vanha painomitta, noin 170 kiloa.",
"Ropokuja": "Ropo tarkoittaa pientä kolikkoa — \"leskenropo\" on tuttu sanonta.",
"Kaupintie": "Lassilan ja Kannelmäen rajaa seuraava kokoojakatu, joka johtaa Kaupinmäen suuntaan.",
"Laurinniityntie": "Laurinniitty ja Laurinmäki ovat vanhoja paikannimiä Lassilan pohjoisosassa.",
"Laurinniitynrinne": "Nimi kuvaa maastoa: Lassila rakentui mäkien ja rinteiden päälle.",
"Niitynperäntie": "Nimi kertoo entisestä maankäytöstä — kadut kulkevat vanhojen niittyjen perillä.",
"Niittykulmantie": "Niittykulma jatkaa Lassilan vanhojen niittynimien sarjaa.",
"Schildtinpolku": "Nimi viittaa kirjailija Runar Schildtiin, jonka mukaan on nimetty myös läheinen Runar Schildtin puisto.",
"Riistavuorenkuja": "Riistavuori on Etelä-Haagan kallioinen mäki, jonka nimi tunnetaan myös alueen palvelutalosta.",
"Mäkipellontie": "Nimi yhdistää maaston ja maanviljelyn: mäkiset pellot olivat Haagan maisemaa ennen rakentamista.",
"Kangaspellontie": "Kangas ja pelto ovat molemmat vanhoja maastonimityksiä — kangas tarkoittaa kuivaa mäntymetsää.",
"Pajuniityntie": "Pajuniitty oli kostea, pajua kasvava niitty ennen asuinkortteleita.",
"Kylänevantie": "Kylä ja neva eli suo yhdistyvät nimessä, joka kertoo Haagan kyläkeskuksen laidan maastosta.",
"Haagan urheilutie": "Katu johtaa Haagan urheilukentän ja liikuntapuiston äärelle.",
"Haagan tori": "Haagan tori on kauppala-ajoista periytyvä pieni torialue Vanhan viertotien varrella.",
"Viertotien aukio": "Aukio Vanhan viertotien varrella, Haagan vanhan liikekeskuksen sydämessä.",
"Tunnelitie": "Nimi tulee radan alittavasta tunnelista — rata halkaisee Haagan kahtia.",
"Rantaradan varsiraitti": "Raitti seuraa rataa: Haagan läpi kulkee sekä Rantarata että Vantaankosken rata.",
"Artturi Kanniston tie": "Artturi Kannisto oli kielitieteilijä, joka tallensi mansikielen sanastoa laajasti.",
"Robert Hermansonin tie": "Robert Hermanson oli oikeustieteilijä ja senaattori, laillisuuden puolustaja sortovuosina.",
"Poliisiasemankuja": "Kuja on nimetty Haagan poliisiaseman mukaan.",
"Bensa-asemankuja": "Arkinen nimi kertoo, mitä kujan päässä on aikanaan ollut."
};
