// Lyhyet faktat Kallion ja Hakaniemen kaduista.
window.KALLIO_FACTS = {
"Hämeentie": "Vanha Hämeeseen johtanut maantie ja Kallion pääväylä. Peruskorjauksen jälkeen kadun keskikaista kuuluu raitiovaunuille ja busseille — yksityisautoille on jätetty vain lyhyet tonttiosuudet.",
"Pitkäsilta": "Pitkäsilta on Helsingin sosiaalihistorian symboli: \"sillan pohjoispuoli\" tarkoitti työväen kaupunkia. Kaiteissa on edelleen vuoden 1918 luodinjälkiä.",
"Siltasaarenkatu": "Hakaniemen ja Kallion selkäranka. Nimi tulee Siltasaaresta, joka oli oma saari ennen täyttömaita.",
"Hakaniemenranta": "Hakaniemen torin ja Kauppahallin rantakatu. Tori on ollut työväen kokoontumispaikka ja vappumarssien lähtöruutu yli sadan vuoden ajan.",
"Hakaniemen torikatu": "Katu reunustaa Hakaniemen toria, jonka vuonna 1914 valmistunut punatiilinen kauppahalli on alueen maamerkki.",
"Hakaniemenkatu": "Lyhyt katu Hakaniemen torin kulmalla, keskellä metroasemien ja raitiolinjojen solmua.",
"Säästöpankinranta": "Nimi tulee Säästöpankin talosta. Rantakatu johtaa Pitkänsillan juurelle.",
"Pitkänsillanranta": "Rantakatu Pitkänsillan pohjoispäässä; täältä avautuu klassinen näkymä Töölönlahden yli keskustaan.",
"Paasivuorenkatu": "Matti Paasivuori oli ammattiyhdistysliikkeen johtohahmo ja kansanedustaja — nimi istuu työväen Kallioon.",
"Miina Sillanpään katu": "Miina Sillanpää oli palvelijattarien asian ajaja ja Suomen ensimmäinen naisministeri.",
"John Stenbergin ranta": "John Stenbergin konepaja oli Sörnäisten rannan suurtyöpaikka; nimi muistaa teollista menneisyyttä.",
"Toinen linja": "Kallion \"linjat\" ovat Suomen omalaatuisin katunimisarja: Ensi linja, Toinen linja, Kolmas linja… Nimet juontuvat 1800-luvun asemakaavan suorista linjoista työväen kaupunginosassa.",
"Ensi linja": "Linjojen ensimmäinen. Kadun päässä seisoo Kallion kirkko, Lars Sonckin vuonna 1912 valmistunut graniittinen jugendkirkko.",
"Kolmas linja": "Yksi Kallion linjoista. Kortteleissa näkyy 1900-luvun alun työväenasuntoarkkitehtuuri pienine asuntoineen.",
"Neljäs linja": "Linjojen neljäs — kadut nousevat rinteessä kohti Torkkelinmäkeä.",
"Viides linja": "Linjasarjan viimeinen; päättyy Kallion ja Alppiharjun rajalle.",
"Porthaninkatu": "Henrik Gabriel Porthan oli 1700-luvun oppinut, jota kutsutaan Suomen historiantutkimuksen isäksi.",
"Porthaninrinne": "Rinne Porthaninkadun jatkeena Hakaniemen suuntaan.",
"Castréninkatu": "Matthias Alexander Castrén tutki suomalais-ugrilaisia kansoja ja kieliä Siperiassa asti.",
"Wallininkatu": "Georg August Wallin oli suomalainen orientalisti, joka matkusti Arabiassa muslimiksi tekeytyneenä.",
"Wallininkuja": "Kuja Wallininkadun kyljessä Kallion kirkon tuntumassa.",
"Suonionkatu": "Suonio oli runoilija ja kansanrunouden tutkija Julius Krohnin kirjailijanimi.",
"Agricolankatu": "Mikael Agricola loi kirjasuomen ja käänsi Uuden testamentin suomeksi 1548.",
"Fleminginkatu": "Klaus Fleming oli 1500-luvun sotapäällikkö ja Suomen käskynhaltija, nuijasodan toinen osapuoli.",
"Franzéninkatu": "Frans Mikael Franzén oli runoilija ja piispa, aikansa arvostetuin ruotsinkielinen lyyrikko Suomessa.",
"Torkkelinkatu": "Torkkelinmäen katujen nimi juontuu Torkkeli Knuutinpojasta, 1200–1300-luvun taitteen Ruotsin valtakunnan marskista.",
"Torkkelinkuja": "Kuja Torkkelinmäen puutalomittakaavaisessa korttelissa.",
"Pengerkatu": "\"Penger\" tarkoittaa rinteeseen rakennettua tasannetta — nimi kuvaa Kallion jyrkkää maastoa.",
"Pengerkuja": "Kuja Pengerkadun varrella Torkkelinmäen rinteessä.",
"Harjutori": "Harjutori oli Kallion oma kauppatori. Nimi tulee harjusta eli mäenselänteestä, jolle kaupunginosa rakennettiin.",
"Harjutorinkatu": "Katu kiertää Harjutorin, jonka laidalla toimi aikoinaan Kallion paloasema.",
"Sakarinkatu": "Torkkelinmäen kaduissa on sarja vanhoja etunimiä — Sakari on yksi niistä.",
"Aadolfinkatu": "Toinen Torkkelinmäen etunimikaduista, kirjoitettuna vanhalla asulla.",
"Helsinginkatu": "Kallion ja Alppiharjun raja ja alueen vilkkain poikkikatu. Kadun varrella on baareja, jotka kuuluvat kaupunginosan kansanperinteeseen.",
"Alppikatu": "Nimi tulee Alppilasta ja Alppipuistosta, jotka saivat nimensä 1800-luvun huvipuistoajan alppimaisemista.",
"Itäinen Alppirinne": "Rinnekatu Alppipuiston laidalla; nimi kertoo maaston jyrkkyydestä.",
"Eläintarhantie": "Eläintarha ei viittaa eläimiin vaan vanhaan puistoalueeseen; Eläintarhan kenttä on yhä Helsingin tunnetuin kaupunkiurheilupaikka.",
"Linnunlauluntie": "Linnunlaulu on Töölönlahden rannan vanha huvila-alue — nimi lupaa juuri sitä, mitä sanoo.",
"Linnunlaulun silta": "Silta johtaa radan yli Linnunlaulun huviloiden ja Kaisaniemen suuntaan.",
"Itäinen Papinkatu": "Papinkadut muistavat seurakunnan maita Kallion kirkon ympärillä.",
"Läntinen Papinkatu": "Papinkatujen läntinen puolisko Kallion kirkon kyljessä.",
"Näkinkuja": "Näkinpuiston mukaan nimetty kuja; näkki on suomalaisen kansanperinteen vesihenki.",
"Näkinsilta": "Silta Näkinpuiston ja Merihaan suuntaan.",
"Merihaankatu": "Merihaka on 1970-luvun betonikaupunginosa meren päällä — arkkitehtuurin ystäville rakas ja vihattu.",
"Saariniemenkatu": "Saariniemi on Siltasaaren vanha niemennimi Tokoinrannan tuntumassa.",
"Viherniemenkatu": "Viherniemi on Siltasaaren pohjoisosan vanha paikannimi.",
"Siltasaarenkärki": "Siltasaaren kärki on Tokoinrannan ja Hakaniemen väliin jäävä puistoinen niemenpää.",
"Vaasankatu": "Kallion kuulu kapea katu, joka on muuttunut epäilyttävästä maineestaan baarien, kirppisten ja kahviloiden riviksi.",
"Kaarlenkatu": "Nimi viittaa Ruotsin kuninkaisiin — Kaarlenkatu ja Kustaankatu muodostavat kuningasparin Kallion nimistössä.",
"Kustaankatu": "Kustaa eli Gustav on toinen Kallion kuningasnimistä Kaarlenkadun rinnalla.",
"Aleksis Kiven katu": "Aleksis Kivi kirjoitti Seitsemän veljestä ja loi suomenkielisen romaanin ja näytelmän perustan.",
"Sturenkatu": "Sture-suku oli Ruotsin mahtavimpia aatelissukuja 1400–1500-luvulla.",
"Kirstinkatu": "Torkkelinmäen etunimikatujen sarjaan kuuluva lyhyt katu.",
"Kaikukuja": "Pieni kuja Hämeentien tuntumassa, nimeltään kuin kaiku.",
"Ässänrinne": "Rinne Torkkelinmäen laidalla; nimi juontuu alueen vanhasta Ässä-korttelista.",
"Papinkuja": "Kuja Papinkatujen välissä Kallion kirkon lähellä."
};
