// Lyhyet faktat Laajasalon kaduista — nimistön teemat ja saaren historia.
window.LAAJASALO_FACTS = {
"Laajasalontie": "Saaren pääväylä ja ainoa maayhteys pohjoiseen. Kaikki Laajasalon liikenne kulkee tämän kadun kautta — myös tuleva Kruunusillat-raitiotie.",
"Yliskyläntie": "Yliskylä on Laajasalon vanha kyläkeskus ja saaren väkirikkain osa; nimi kertoo kylän sijainnista saaren ylärinteellä.",
"Yliskylän puistokatu": "Yliskylän uudistuneen keskustan pääkatu, jonka varrelle on noussut 2020-luvulla uusia kerrostaloja ja palveluita.",
"Yliskyläkaari": "Yliskylän kortteleita kiertävä katu.",
"Koirasaarentie": "Katu johtaa Kruunuvuorenrantaan ja on nimetty Koirasaaren mukaan; varrella on entisiä öljysataman alueita, jotka muuttuvat asuinkortteleiksi.",
"Hevossalmentie": "Hevossalmi on Laajasalon ja Santahaminan välinen kapea salmi. Sen yli johtaa silta, ja rannassa on suosittu uimaranta.",
"Kirkkosalmentie": "Kirkkosalmi erottaa Laajasalon Tammisalosta; nimi viittaa kirkkomatkoihin, jotka tehtiin aikoinaan vesitse.",
"Reposalmentie": "Reposalmi on saaren pohjoisrannan salmi — Laajasalon nimistö on täynnä salmia, niemiä ja saaria.",
"Kuvernöörintie": "Nimi muistaa Laajasalon kartanon aikaa, jolloin saaren maita hallitsivat varakkaat kaupunkilaiset ja virkamiehet.",
"Kuvernöörinkuja": "Kuja Kuvernöörintien kyljessä Yliskylän kortteleissa.",
"Henrik Borgströmin tie": "Henrik Borgström oli 1800-luvun helsinkiläinen kauppaneuvos ja mesenaatti, joka omisti maita Laajasalossa.",
"Henrik Borgströmin polku": "Polku Borgströmin tien varrella; suku vaikutti saaren kartanohistoriaan.",
"Borgströminkuja": "Kuja Borgströmin nimiperheessä Yliskylässä.",
"Axel Lindbergin tie": "Axel Lindberg oli Laajasalon kartanon isäntäväkeen kuulunut vaikuttaja 1800-luvun lopulla.",
"Willebrandintie": "Nimi juontuu von Willebrand -suvusta, joka omisti Laajasalon kartanon maita.",
"Mellinintie": "Mellin-suku kuului Laajasalon kartanon historiaan; katu on Yliskylän vanhemmalla pientaloalueella.",
"Reiherintie": "Reiher-suvun mukaan nimetty katu Yliskylän länsiosassa.",
"Gunillantie": "Gunilla on vanha ruotsalainen etunimi; Gunillankallio ja Gunillanpuisto ovat saaren tunnettuja paikannimiä.",
"Gunillanraitti": "Raitti Gunillan kortteleissa — Yliskylän kevyen liikenteen reittejä kutsutaan raiteiksi ja poluiksi.",
"Sarvastonkaari": "Sarvasto on Laajasalon eteläosan vanha paikannimi; kaari kiertää asuinkortteleita.",
"Isonsarvastontie": "Isosarvasto on Jollaksen puoleinen niemi — nimistö seuraa saaren omia maastonimiä.",
"Jollaksentie": "Jollaksen pääväylä. Jollas on saaren itäosan pientaloalue, jonka nimi tulee jollasta eli pienestä veneestä.",
"Jollaksenaukio": "Jollaksen pieni palveluaukio pientaloalueen keskellä.",
"Fregattitie": "Jollaksen kadut on nimetty purjelaivatyyppien mukaan: fregatti, kuunari, priki, kaljaasi ja kutteri.",
"Kuunaritie": "Kuunari on kahden tai useamman maston purjelaiva — yksi Jollaksen laivanimistä.",
"Prikitie": "Priki on kaksimastoinen purjelaiva; nimi jatkaa Jollaksen merellistä sarjaa.",
"Kaljaasitie": "Kaljaasi oli suomalaisten rannikkoseutujen työjuhta — purjealus, jolla kuljetettiin tavaraa.",
"Kutteritie": "Kutteri on pieni yksimastoinen alus; Jollaksen laivanimisarjan jäsen.",
"Mesaanikuja": "Mesaani on purjelaivan perimmäinen masto — Jollaksen nimistö on puhdasta merenkulun sanastoa.",
"Takilatie": "Takila tarkoittaa purjelaivan mastojen ja köysien kokonaisuutta.",
"Kölitie": "Köli on laivan pohjan kantava runko-osa.",
"Ruoritie": "Ruori jatkaa Jollaksen merellistä nimistöä.",
"Ruorimiehentie": "Ruorimies ohjaa laivaa — nimistö kuljettaa merimiesammatteja kadulta kadulle.",
"Rannikkolaivurintie": "Rannikkolaivuri oli rannikkoliikenteen kipparin virallinen pätevyys.",
"Keulakuvantie": "Keulakuva oli purjelaivan keulaan veistetty hahmo, joka toi onnea matkalle.",
"Itätuulentie": "Jollaksessa on myös tuulten sarja: itätuuli, puhuri, puuska ja laitatuuli.",
"Puhuritie": "Puhuri on kova tuuli — Jollaksen tuulinimistöä.",
"Purjetuulentie": "Purjetuuli on merenkulkijan paras ystävä.",
"Laitatuulenkaari": "Laitatuuli puhaltaa aluksen kylkeen; nimi kuuluu Jollaksen tuuliteemaan.",
"Puuskaniementie": "Puuskaniemi on Jollaksen niemi, jonka nimi yhdistää maaston ja tuulen.",
"Pääskylahdentie": "Pääskylahti on Jollaksen rannan lahti — saaren nimistö on paikannimien kartta.",
"Hepokalliontie": "Hepokallio on Jollaksen kallioinen kohta; hepo tarkoittaa hevosta.",
"Tonttuvuorentie": "Tonttuvuori on Jollaksen mäki, jonka nimi on jäänyt kansanperinteestä.",
"Villinginsalmentie": "Villinginsalmi erottaa Laajasalon Villingin saaresta, joka on säilynyt huvilasaarena ilman tiestöä.",
"Matosaarentie": "Matosaari on pieni saari Jollaksen rannikolla.",
"Poikasaartentie": "Poikasaaret ovat Jollaksen edustan saaria.",
"Furuvikintie": "Furuvik eli Mäntylahti on vanha ruotsinkielinen rantanimi.",
"Karoliinintie": "Vanhojen etunimien mukaan nimettyjä katuja on Jollaksen vanhemmalla huvila-alueella.",
"Viiktorpantie": "Torppanimet kertovat, että Jollaksessa oli kartanon torppia ennen huviloita ja omakotitaloja.",
"Vanha sotilastie": "Nimi muistaa Santahaminan varuskunnan aikaisia sotilasreittejä saaren läpi.",
"Haakoninlahdenkatu": "Kruunuvuorenrannan uuden kaupunginosan pääkatu. Alue rakentuu entisen öljysataman paikalle 2010-luvulta alkaen.",
"Stansvikin rantakatu": "Stansvikin kartano ja sen historiallinen puisto ovat Kruunuvuorenrannan naapurissa, suojeltuna keitaana uusien kortteleiden vieressä.",
"Hopeakaivoksentie": "Kruunuvuoressa toimi 1700-luvulla hopeakaivos — kaupunginosan nimistö muistaa kaivostoiminnan.",
"Kaivospolku": "Kruunuvuoren vanhan hopeakaivoksen muisto näkyy alueen polkujen nimissä.",
"Kaivossepänkuja": "Kaivossepät työskentelivät Kruunuvuoren kaivoksella 1700-luvulla.",
"Kultakruununkaari": "Kruunuvuoren nimistö yhdistää kruunun ja kaivosaiheet uuden kaupunginosan kortteleissa.",
"Kultaveneenkatu": "Kruunuvuorenrannan uusien katujen nimissä on tarunhohtoinen sävy.",
"Saaristolaivastonkatu": "Nimi muistaa Ruotsin ajan saaristolaivastoa, joka operoi Helsingin edustan vesillä.",
"Laivakoirankatu": "Laivakoira oli aluksen onnenoloinen jäsen; Kruunuvuorenrannan nimistö on leikkisää.",
"Astridinkatu": "Kruunuvuorenrannassa on sarja naisten etunimiä kantavia katuja.",
"Disankatu": "Disa on vanha ruotsalainen naisennimi — yksi Kruunuvuorenrannan etunimikaduista.",
"Mirandankatu": "Miranda kuuluu Kruunuvuorenrannan etunimikatujen sarjaan.",
"Frejankuja": "Freja on pohjoismaisen mytologian jumalatar.",
"Ellidankuja": "Ellida oli tarunomainen laiva pohjoismaisessa kertomusperinteessä.",
"Kaitalahdentie": "Kaitalahti on Laajasalon länsirannan pientaloalue kapean lahden pohjukassa.",
"Tahvonlahdenniemi": "Tahvonlahti on Laajasalon länsirannan lahti; niemi työntyy Kruunuvuorenselälle.",
"Vuorilahdentie": "Vuorilahti on saaren länsirannan lahti — rantojen nimet ovat Laajasalossa myös katujen nimiä.",
"Kallioniementie": "Kallioniemi on Laajasalon rantaniemi, jossa on partiolaisten leirialue.",
"Isosaarentie": "Isosaari on Helsingin edustan linnoitussaari, joka avattiin yleisölle vasta 2010-luvulla.",
"Orisaarentie": "Orisaari on Laajasalon pohjoispuolen saari; Kruunusiltojen reitti kulkee sen kautta.",
"Kanavasillantie": "Nimi viittaa kanavaan ja siltaan saaren pohjoisosassa.",
"Kanavamäki": "Kanavamäki on Yliskylän pohjoisosan asuinalue kanavan tuntumassa.",
"Satulamäentie": "Satulamäki on Yliskylän mäennimi; maasto vaihtelee saarella jyrkästi.",
"Ilomäentie": "Ilomäki on Laajasalon mäennimi — nimi ilahduttaa jo itsessään.",
"Humalniementie": "Humalniemi on vanha rantanimi; humala viittaa kasviin, jota kasvatettiin oluen valmistukseen.",
"Itäniityntie": "Itäniitty oli kartanon niittymaata saaren itäosassa.",
"Pastorintie": "Nimi muistaa saaren kirkollista historiaa ja pappien kulkureittejä.",
"Suomensuontie": "Suomensuo on Laajasalon suoalue, joka on osin kuivatettu rakentamisen tieltä.",
"Tuurholmanpolku": "Tuurholma eli Turholm on Laajasalon kartanon vanha nimi; kartanon päärakennus on säilynyt Tullisaaressa.",
"Etanapolku": "Laajasalossa on pieni sarja hyönteis- ja pikkueläinaiheisia polkuja: etana, muurahainen, kiiltomato ja tuhatjalkainen.",
"Muurahaisenpolku": "Osa Yliskylän pikkueläinpolkujen sarjaa.",
"Kiiltomadonpolku": "Kiiltomato hehkuu kesäöissä — yksi Yliskylän eläinaiheisista poluista.",
"Tuhatjalkainen": "Harvinaisen hauska kadunnimi: pelkkä eläin ilman tie- tai polku-päätettä.",
"Ryytikuja": "Ryyti eli mauste — Yliskylässä on myös pieni sarja kasvi- ja mausteaiheisia nimiä.",
"Kuminakuja": "Kumina kuuluu Yliskylän mausteaiheisiin kadunnimiin.",
"Marunapolku": "Maruna on voimakastuoksuinen yrtti.",
"Haravakuja": "Yliskylän puutarha-aiheisia nimiä: harava, umpiaita ja ryytimaa.",
"Umpiaidanpolku": "Umpiaita on tiivis pensasaita — nimi sopii pientaloalueelle.",
"Koulutanhua": "\"Tanhua\" on vanha sana pihatielle; katu johtaa koulun tuntumaan."
};
