// Urbaanin moodin faktat — pilke silmäkulmassa, kaupunkilegendojen puolella.
window.HKI_PARTY_FACTS = {
"Aleksanterinkatu": "Päivällä ostoskatu, illalla viinibaarien rivi Vennistä Blandaan. Uudenvuodenaattona koko kansan kuohuvakäytävä Senaatintorille — ja aina joku, joka avaa pullon liian aikaisin.",
"Pohjoisesplanadi": "Trillby & Chadwick piileskelee vanhassa etsivätoimistossa: ovea ei löydä, ellei tiedä sen olevan siellä. Kadun toisessa päässä Mann's Street laulaa karaokea aamuun.",
"Eteläesplanadi": "Le Bloom ja Charm hoitavat yön, Espan lava päivän. Vappuna puistossa on niin täyttä, että oma piknikviltti on statussymboli.",
"Mannerheimintie": "Fellows, irkkupubit ja Mann's Street samalla kadulla. Stockmannin kello on virallinen tapaamispaikka ja epävirallinen paikka odottaa 40 minuuttia.",
"Kaivokatu": "Hercules ja On The Rocks vetävät yötä, Milliklubi hoitaa loput. Aseman kivimiehet ovat nähneet jokaisen väärän viimeisen junan eivätkä ole kertoneet kenellekään.",
"Keskuskatu": "Iguana ja Wall St. Bar päivällä, Hercules illalla. Aallon marmoripihalla kahvi maistuu kuin sinulla olisi taidehistorian maisteri.",
"Mikonkatu": "Tokio Karaoke, Bardem ja Bar All In sadan metrin säteellä. Kaupungin tehokkain \"vielä yksi\" -putki asemalta Esplanadille.",
"Kluuvikatu": "Helsinki Shot Bar tekee juuri sen mitä nimi lupaa: shotit ovat halpoja, joskus liiankin halpoja, ja aamun katumus on ilmainen bonus.",
"Vuorikatu": "Oluthuone Kaisla, Juova Hanahuone ja Roudaribaari IHME — kolme täysin eri elämäntapaa kolmessa korttelissa. Roudaribaarissa tarinat ovat aina isompia kuin bändit.",
"Vilhonkatu": "Oluthuone Kaislassa on enemmän hanoja kuin ehdit maistaa. Bar Chaplin on sen vieressä siltä varalta, ettet halunnut valita.",
"Yliopistonkatu": "Haalarijono voittaa lounasjonon pituudessa, ja molemmat päättyvät Helsinki Shot Bariin. Kampuksen lähin oppitunti on nimeltään \"yksi vielä\".",
"Kaisaniemenkatu": "Molly Malone'sissa livemusiikki ei lopu koskaan, ja Kaisaniemen puisto toimii kesällä kaupungin suurimpana terassina ilman yhtäkään terassia.",
"Hallituskatu": "Ei yhtään baaria — mutta uudenvuodenaattona täällä seisoo puoli Helsinkiä odottamassa neljän minuutin ilotulitusta muovimukin kanssa.",
"Snellmaninkatu": "Pataässä on Kruununhaan oma nurkkakuppila, jossa kaikki tuntevat toisensa ja jokainen tuntee jonkun, joka oli täällä silloin kun se juttu tapahtui.",
"Unioninkatu": "Tuomiokirkon portaat: kaupungin klassisin esibilepaikka. Oma juoma, ilmainen näköala, ja aina joku, joka ottaa kuvan väärästä suunnasta.",
"Fabianinkatu": "Thirsty Scholar ja Yökyöpeli ovat kirjaston naapureita, mikä on selvästi kaupunkisuunnittelun vitsi. Kirjastokortti ja anniskelu samalla korttelilla.",
"Sofiankatu": "Mukulakivet plus korot plus Blanda kello kaksi = kaupungin haastavin 80 metriä. Legendan mukaan yksi kenkä jää tänne joka viikonloppu.",
"Jaakonkatu": "Bar Ihku ja Hemingway's ovat kadun päissä kuin kaksi eri elämänvalintaa. Kolmas vaihtoehto on Bierhuis Rotterdam, eli lisää oluttyyppejä kuin osaat lausua.",
"Simonkatu": "El Patron hoitaa yön, Simonkenttä päivän. Lasipalatsin aukio on kesällä kaupungin olohuone ja talvella tuulitunneli.",
"Erottajankatu": "Liberty Or Death sekoittaa cocktailit vakavalla naamalla, Rymy-Eetu tarjoilee litran tuopin ilman naamaa lainkaan. Karaoke Bar Erottaja odottaa siltä varalta, että molemmat onnistuivat.",
"Pohjoinen Rautatiekatu": "Presidentti Club, Kraken ja Helkan Baari radan varressa. Täällä lasketaan, ehtiikö lähijunaan — ja päätetään ettei ehdi.",
"Eteläinen Rautatiekatu": "Presidentti Club ja Bar Ihku kadun kulmilla. Kampin terminaali on kymmenen metrin päässä, mikä on sekä hyvä että erittäin huono asia.",
"Mariankatu": "Nolla baaria. Kruununhaassa juhlitaan kotona, ja naapuri soittaa isännöitsijälle ennen kuin biisi pääsee kertosäkeeseen.",
"Kirkkokatu": "Ei anniskelua, mutta Tuomiokirkon takapiha on ilmainen. Kaupunkilegenda kertoo kuorosta, joka harjoitteli portailla kello kolme yöllä.",
"Rauhankatu": "Pataässä pelastaa kadun, joka muuten olisi täysin raitis. Kansallisarkiston lukusali sulkeutuu juuri kun ilta alkaa.",
"Liisankatu": "Harry's Bar ja Star Cafe: kaksi paikkaa, joissa kello ei näytä olevan seinällä lainkaan. Täältä ilta jatkuu aina Hakaniemen suuntaan.",
"Meritullinkatu": "Ei yhtään kapakkaa, vain jyrkkä mäki rantaan. Alamäki on helppo, ylämäki neuvottelee kanssasi kello kolme.",
"Pohjoisranta": "Ei baareja, mutta veneet, meri ja Uspenski vastarannalla. Kaupungin paras katu kävellä kotiin ja kuvitella olevansa elokuvassa.",
"Vironkatu": "Sake Bar & Izakaya tarjoaa sakea kadulla, joka on nimetty Viron mukaan. Kaupunkilegenda: joku on todella lähtenyt täältä Tallinnaan ilman matkalaukkua.",
"Ritarikatu": "Ritarihuone oli 1800-luvun VIP-alue: ovimies, pukukoodi ja vieraslista. Nykyään kadulla ei ole baaria lainkaan, mikä on eräänlainen jatkumo.",
"Maurinkatu": "Nolla anniskelupaikkaa, mutta Tervasaari kadun päässä on kaupungin klassisin piknikkallio. Ota mukaan roskapussi, älä kaiutinta.",
"Kristianinkatu": "Kantakaupungin vanhin puutalo on täällä. Se on selvinnyt kahdesta sadasta vuodesta ja lukemattomista naapurin kotibileistä ilman valitusta.",
"Oikokatu": "Katu oikaisee ruutukaavan vinosti — eli tekee juuri sen, mitä sinäkin yritit tehdä matkalla jatkoille. Ero on, että katu onnistuu.",
"Luotsikatu": "Katajanokan jugendjulkisivuilla kyyhöttää karhuja ja satuolentoja. Kello kaksi yöllä ne näyttävät katsovan takaisin.",
"Kruununhaankatu": "Ei baareja, ei terassia, ei toivoa. Kruununhaka on kaupunginosa, jossa kotibileet loppuvat kello 22 ja kaikki ovat siitä helpottuneita.",
"Kanavakatu": "Key West Pub ja Beaky Basterd & Co. matkalla Katajanokan kärkeen, jossa Allas Sea Pool tarjoaa saunan, altaan ja drinkin. Järjestys on vapaa, seuraukset eivät.",
"Kasarmikatu": "Kaarle XII eli \"Kalle\" on kadun instituutio: kolme kerrosta, kolme eri vuosikymmentä ja jono, joka ei koskaan lyhene. Le Bloom hoitaa ne, jotka eivät jaksaneet jonottaa.",
"Korkeavuorenkatu": "Sea Horse eli \"Sikala\" on legenda: silakat, kaljalasit ja tarinat kirjailijoista, jotka kuulemma nukkuivat pöydän alla. Goldfish ja The Last Drop jatkavat siitä.",
"Eteläranta": "Bar Haven ja Kauppatori. Krapula-aamiaisen virallinen sarja: lohikeitto Vanhassa kauppahallissa, sitten teeskennellään että se oli suunniteltua.",
"Pohjoinen Makasiinikatu": "Kaarle XII on kulman takana ja Yökyöpeli nimensä mukaisesti auki. Muuten katu on suurlähetystöjä, joissa juhlitaan kutsuvieraille ja ilman tarinoita.",
"Eteläinen Makasiinikatu": "Lilla e. hoitaa cocktailit, Makasiiniranta hoitaa kaavakiistan. Molemmat vetävät yllättävän paljon väkeä.",
"Ludviginkatu": "The Last Drop, Pub Ludvig ja Rymy-Eetu käytännössä samassa risteyksessä. Tämä on kaupungin lyhyin katu, jolla voi tehdä kolmen baarin kierroksen märkänä.",
"Pieni Roobertinkatu": "G Livelab soittaa livenä niin hyvällä äänellä, että se on lähes epäreilua. Black Door ja Bar Mate hoitavat sen jälkeen, kun korvat kestävät taas.",
"Tehtaankatu": "Petisco ja Basbas Kulma ovat kadun ylpeys, Venäjän suurlähetystö sen otsikko. Ainoa katu, jolla voi sanoa \"nähdään lähetystön kohdalla\" ja kaikki tietävät missä.",
"Merikatu": "Ei baaria, mutta Merisatamanrannan kalliot ovat kaupungin suurin luvaton viiniterassi. Auringonlasku on ilmainen, pantti ei.",
"Laivurinkatu": "Pinocchio Vineria ja Ravintola Viiskulma. Laivurinrinne on niin jyrkkä, että se on kirjaimellisesti este toiselle kierrokselle.",
"Kapteeninkatu": "Sea Horse eli Sikala on täällä, ja sen terassi on kaupungin demokraattisin: kirjailija, rakennusmies ja turisti samassa pöydässä.",
"Ratakatu": "Rööperin Hopstop ja B.B.Badger&Co. Kadun päässä Johanneksenkirkon portaat, kesäöiden yleisimmät jatkot ilman sisäänpääsymaksua.",
"Ullanlinnankatu": "B.B.Badger&Co. on käytännössä kadun ainoa syy jäädä ulos. Vappuna Ullanlinnanmäki muuttuu kaupungin suurimmaksi piknikiksi ja palaa sitten uneen vuodeksi.",
"Vuorimiehenkatu": "Sea Horse alamäessä, Pinocchio Vineria ylämäessä. Kadun huipulla on aina se yksi kaveri, jonka parvekkeelta näkyy meri ja jonka bileisiin kaikki haluavat.",
"Tähtitorninkatu": "Nolla baaria, mutta Tähtitorninvuori on kaupungin paras auringonlaskukatsomo. Vappuaattona täällä on enemmän kuohuvaa kuin koko Esplanadilla.",
"Puistokatu": "Johtaa Kaivopuistoon, jossa Kaivohuone on ollut kylpyläkasino, tanssilava ja kesäklubi. Vappuna koko puisto on tanssilattia, jonka lattia on mutaa.",
"Huvilakatu": "Eiran valokuvatuin katu. Kello yksi yöllä kuiskaus kantaa kolme korttelia — muista se, jos jatkot ovat täällä.",
"Neitsytpolku": "Suurlähetystöjen huviloita ja korkeita pensasaitoja. Bileet ovat aitojen takana, eikä sinua ole kutsuttu. Legendan mukaan yksi vieras kiipesi silti.",
"Pietarinkatu": "Punavuoren kahvila- ja vintagekatu, joka muuttuu illalla lähibaarien reitiksi. Kaikki tuntevat kaikki, mikä on sekä kaupungin paras että pahin puoli.",
"Tarkk'ampujankatu": "Ravintola Viiskulma kadun päässä. Vanha kasarmikulma, jossa nykyään ammutaan vain valokuvia auringonlaskusta Johanneksenpuistossa.",
"Rikhardinkatu": "Pub Ludvig, The Last Drop ja Kaarle XII kävelymatkan päässä. Kirjasto sulkeutuu, baari avautuu — kaupunkisuunnittelua parhaimmillaan.",
"Ullankatu": "Ursan tähtitorni pitää yleisöiltoja: kaupungin ainoa paikka, jossa katsotaan ylöspäin eikä kyse ole hinnoista.",
"Laivasillankatu": "Toisella puolella Kaivopuiston puut, toisella risteilijät. Kesäisin täällä kävellään jäätelö kädessä ja väitetään suunnittelevansa rauhallista iltaa.",
"Bulevardi": "Room Blvd ja Kiska kadun varrella, Koffin puisto keskellä. Puisto on kaupungin klassisin piknikkenttä ja epävirallinen ulkoilmaklubi ilman lupaa.",
"Uudenmaankatu": "Rymy-Eetu, Bier-Bier, Street Pride Bar ja Barcelo. Etäisyys seuraavaan baariin: 20 metriä. Etäisyys hyvään päätökseen: pidempi.",
"Iso Roobertinkatu": "\"Ropa\": Jackie, Black Door, Tommy Knocker ja The Riff samalla kävelykadulla. Terassit avautuvat huhtikuussa, koska optimismi on ilmaista.",
"Fredrikinkatu": "Oluthuone Angleterre, Tales Wine Bar ja Hemingway's samassa suorassa. Kadun pituus riittää siihen, että ehdit muuttaa mielesi kolme kertaa.",
"Albertinkatu": "Punavuoren Ahven, Bar Bronco ja Merimies pub. Nurkkakuppiloiden kotikatu, jossa kukaan ei kysy mitä teet työksesi.",
"Annankatu": "Bar Loose on rockin pyhättö ja Gate A21 cocktailien: saman kadun kaksi ääripäätä. A21:ssä drinkillä on tarina, Loosessa sinulla.",
"Yrjönkatu": "Tornin Ateljee Bar on kaupungin paras näköala ja tunnetuin ahdas vessa. Alhaalla O'Malleys, Ølhus København ja G Livelab hoitavat loput yöstä.",
"Kalevankatu": "Villi Wäinö, Bricco ja Oluthuone Angleterre. Sopivasti sivussa, ettei jonoa ole, mutta riittävän lähellä, ettei taksia tarvitse.",
"Eerikinkatu": "Alcatraz Club, Leijuva Lahna ja Pub Peräkammari. Nimi viittaa kuninkaan kiertomatkaan, ja kierros tehdään yhä samassa järjestyksessä joka viikko.",
"Lönnrotinkatu": "Boothill Rock Club, 8-Bit Taproom ja Pikkulintu Ruttopuisto. Nimi \"Ruttopuisto\" tulee vuoden 1710 hautausmaasta — ja kesäisin siellä istuu satoja ihmisiä, jotka eivät tiedä sitä.",
"Punavuorenkatu": "Punavuoren Ahven on kadun instituutio. Kaupunginosan boheemi maine perustuu siihen, että kaikki tuntevat kolme samaa baaria ja väittävät löytäneensä ne itse.",
"Pursimiehenkatu": "Basbas Kulma ja Ravintola Viiskulma. Punavuoren rauhallisempi puoli, jossa pöytä on täynnä ilman että kukaan on postannut siitä.",
"Merimiehenkatu": "Merimies pub ja Bob's Laundry samalla kadulla: toinen tarjoaa kaljan, toinen cocktailin pesulan nimissä. Molemmat toimivat.",
"Malminkatu": "Wanha kettu pitää kadun pinnalla. Muuten tämä on reitti Maria 01:n after workista jonnekin, mistä ei enää muista.",
"Salomonkatu": "Teerenpeli, Aussie bar ja Pub Ikkuna. Kampin terminaali vieressä, eli illan tärkein infrastruktuuri kun bussi on ainoa jäljellä oleva vaihtoehto.",
"Hietalahdenranta": "Hemingway's Hietalahti ja Malja. Kirpputori päivällä, kauppahallin ravintolat illalla — sama kortteli, kaksi täysin eri elämää.",
"Lapinlahdenkatu": "Apotek viinibaari ja Mendocino. Kadun päässä Lapinlahti: vanha sairaala, jossa on nyt kahvila, sauna ja meri. Paras vaihtoehto sille, ettei jaksa keskustaan.",
"Runeberginkatu": "Bar Teos, Bhangra ja Vastarannan Kiiski. Töölössä juhlitaan aikaisemmin, hiljempaa ja viinilasi kerrallaan — ja ollaan aamulla töissä.",
"Arkadiankatu": "Tales Wine Bar ja Presidentti Club. Kadun päässä Eduskuntatalo, eli ainoa katu Helsingissä, jolla \"jatkot\" voi tarkoittaa istuntoa aamuviiteen.",
"Museokatu": "Storyville soittaa jazzia kellarissa ja St Urho's Pub hoitaa loput. Kansallismuseo naapurissa antaa illalle sivistyneen alibin.",
"Töölönkatu": "Bar Teos, Storyville ja St Urho's Pub. Töölön torilla markkinat lauantaina, naapurustobaarit iltaisin, eikä kukaan jonota mihinkään.",
"Mechelininkatu": "Laiska Karhu ja Bar Favela. Kadun paras pyörätie tuottaa myös kaupungin yleisimmän huonon päätöksen: \"kyllä minä ajan\".",
"Nervanderinkatu": "Ei ainuttakaan baaria. Täällä esibileet ovat neljä ihmistä, levysoitin ja naapuri, joka tulee mukaan kello 23.",
"Apollonkatu": "Ritz Biljardi: kadun ainoa paikka, jossa voi häviää sekä pelin että illan. Kadut on nimetty antiikin jumalten mukaan, mikä on kova pohja bileteemalle.",
"Aurorankatu": "Storyville ja Tales Wine Bar kulmilla. Aamuruskon jumalattaren katu, jonka ohi kävelet juuri kun taivas alkaa vaaleta.",
"Dagmarinkatu": "St Urho's Pub pelastaa kadun. Nimetty keisarinnan mukaan, joka tuskin arvasi päätyvänsä irkkupubin osoitteeseen.",
"Cygnaeuksenkatu": "Nolla anniskelupaikkaa. Kansakoulun isä tuskin suunnitteli, että hänen kadullaan opitaan lähinnä sekoittamaan drinkkejä keittiössä.",
"Eteläinen Hesperiankatu": "Ritz Biljardi kulman takana, Hesperianpuisto edessä. Kesäöiden paras oikoreitti Töölönlahdelle, jossa istutaan kalliolla kaiuttimen kanssa.",
"Pohjoinen Hesperiankatu": "Ei baareja, mutta täältä alkaa Töölönlahden kierros — kaupungin klassisin \"kävellään vielä hetki\" -lenkki kello kaksi yöllä.",
"Temppelikatu": "Temppeliaukion kirkko on louhittu kallioon ja sen akustiikka on legendaarinen. Ainoa paikka Töölössä, jossa bassot on virallisesti hyväksytty.",
"Sandelsinkatu": "Ei kapakkaa, mutta vanhassa koulussa toimii kulttuurikeskus: konsertteja ja yllättävän hyviä iltoja ilman ovimiestä ja narikkamaksua.",
"Topeliuksenkatu": "Tinku on kadun oma pikkubaari. Sadunkertojan mukaan nimetty katu, jonka illan tarinat ovat harvoin yhtä opettavaisia.",
"Caloniuksenkatu": "Bhangra, Mr. Don ja Laiska Karhu. Kesäöinä täällä kävelee enemmän ihmisiä kuin päivällä, ja kaikki ovat matkalla samaan suuntaan.",
"Pohjoinen Rautatiekatu ": "",
"Eteläinen Rautatiekatu ": ""
};
delete window.HKI_PARTY_FACTS["Pohjoinen Rautatiekatu "];
delete window.HKI_PARTY_FACTS["Eteläinen Rautatiekatu "];
