// Lyhyet faktat kaduista — apuna oppimiseen.
window.HKI_FACTS = {
"Aleksanterinkatu": "Nimetty keisari Aleksanteri I:n mukaan ja Helsingin kauppakatujen kuningatar. Marraskuun lopulla täällä avataan joulukatu, ja koko katu sytytetään valoihin kerralla.",
"Pohjoisesplanadi": "Kaupungintalo, kirjakauppoja ja Kappelin terassi. Kadun itäpäässä seisoo Havis Amanda, jolle lakitetaan ylioppilaslakki joka vappuaatto.",
"Eteläesplanadi": "Esplanadin puiston eteläreuna. Länsipäässä Svenska Teatern, ja kesällä Espan lavalla soi ilmaista musiikkia keskellä työpäivää.",
"Mannerheimintie": "Helsingin pisin katu, vuoteen 1942 Heikinkatu. Varrella Kiasma, Musiikkitalo ja Oodi — ja Stockmannin kello, klassinen \"nähdään kellon alla\" -tapaamispaikka.",
"Kaivokatu": "Päärautatieaseman edusta. Aseman ovia vahtivat Emil Wikströnin Lyhdynkantajat eli kivimiehet, joita helsinkiläiset kutsuvat aseman kivimiehiksi.",
"Keskuskatu": "Kävelykatu, jolla on kaksi Alvar Aallon taloa: Rautatalo marmorisen sisäpihakahvilan kanssa ja Kirjatalo, jossa on Akateeminen kirjakauppa.",
"Mikonkatu": "Ruotsiksi Mikaelsgatan. Kapea oikotie asemalta Esplanadille, ja Kämp Galleria avautuu kadun kulmasta.",
"Kluuvikatu": "Kluuvi tarkoittaa umpeen kasvanutta merenlahtea — täällä oli ennen vettä. Nyt katu on kauppojen ja kauppakeskuksen reunustama.",
"Vuorikatu": "Nimi tulee kadun pohjoispäässä kohoavasta kallioselänteestä — mäki jyrkkenee Kaisaniemen suuntaan. Rauhallinen oikotie Kluuvin ja Kaisaniemen välillä.",
"Vilhonkatu": "Rautatientorin pohjoislaidan pikkukatu, josta lähtee reitti Kaisaniemen puistoon ja kasvitieteelliseen puutarhaan.",
"Yliopistonkatu": "Nimi kertoo naapureista: Helsingin yliopiston päärakennus ja Porthania ovat kadun molemmin puolin, ja lounasaikaan katu on täynnä opiskelijoita.",
"Kaisaniemenkatu": "Kaisaniemi on nimetty ravintoloitsija Cajsa Wahllundin mukaan, joka piti alueella suosittua ravintolaa 1800-luvun alussa.",
"Hallituskatu": "Kulkee Senaatintorin pohjoislaidassa. Vastapäätä kohoaa Engelin suunnittelema Kansalliskirjasto, yksi kaupungin kauneimmista saleista.",
"Snellmaninkatu": "J. V. Snellmanin mukaan. Varrella Suomen Pankki ja Säätytalo, jonka portailla on kuvattu lukemattomia uutislähetyksiä.",
"Unioninkatu": "Nimi annettiin 1819 muistoksi Suomen ja Venäjän \"unionista\". Tuomiokirkon portaat kadun varrella ovat kaupungin suosituin auringonlaskupaikka.",
"Fabianinkatu": "Kadun päässä on Kaisa-talo, yliopiston pääkirjasto: palkittu lasijulkisivu ja hiljaisin lukusali keskustassa.",
"Sofiankatu": "Mukulakivinen pikkukatu Senaatintorilta Kauppatorille. Talossa numero 4 toimi pitkään kaupunginmuseo ja lasten Kaupunkiverstas.",
"Jaakonkatu": "Pieni katu Kampin kulmalla, hyvä oikotie kun Mannerheimintien liikenne alkaa väsyttää.",
"Simonkatu": "Kadun kulmalla on Lasipalatsi ja Amos Rex, jonka pyöreät kattoikkunat pullistuvat aukion pinnasta kuin kuplat.",
"Erottajankatu": "Nimi tulee vanhasta palokujasta, joka \"erotti\" puutalokorttelit tulipalon varalta. Nykyään katu tunnetaan baareistaan ja yöelämästään.",
"Mariankatu": "Kruununhaan empire-julkisivut ovat niin ajattomia, että länsielokuvissa niillä on esitetty Pietaria ja Neuvostoliittoa.",
"Kirkkokatu": "Kulkee Tuomiokirkon takaa Kruununhakaan. Kirkon takapiha on hiljaisempi ja valokuvattavampi kuin kuulu etuportaikko.",
"Rauhankatu": "Varrella Kansallisarkisto, jonne on talletettu Suomen vanhimmat asiakirjat — ja jonne pääsee lukusaliin kuka tahansa.",
"Liisankatu": "Nimetty keisarinna Elisabetin mukaan. Kadun päästä avautuu näkymä Pohjoisrannan venesatamaan.",
"Meritullinkatu": "Nimi muistuttaa vanhasta meritullista. Katu laskee jyrkästi rantaan, joten kesäaamuna täällä näkee merisumua.",
"Pohjoisranta": "Kruununhaan rantabulevardi, jossa veneet keinuvat aivan jalkakäytävän vieressä. Vastarannalla kohoaa Uspenskin katedraalin punatiili.",
"Vironkatu": "Nimetty Viron mukaan. Kruununhaan kulmilla on kaupungin tiheimmin säilynyttä 1800-luvun puu- ja kivikaupunkia.",
"Ritarikatu": "Yksi Helsingin vanhimmista kaduista. Varrella Ritarihuone, jossa aateliset kokoontuivat ennen kuin säädyt lakkautettiin.",
"Maurinkatu": "Kruununhaan pohjoinen pikkukatu. Täältä on lyhyt matka Tervasaaren kannakselle, joka on paikallisten piknikkallio.",
"Kristianinkatu": "Numerossa 12 on Ruiskumestarin talo, kantakaupungin vanhin puutalo vuodelta 1818 — museo, jossa aika on pysähtynyt 1860-luvulle.",
"Oikokatu": "Nimi kertoo tehtävänsä: katu oikaisee ruutukaavan läpi vinosti, mikä on Helsingissä harvinaista.",
"Luotsikatu": "Katajanokan jugendkorttelin sydämessä. Julkisivuilla kyyhöttää karhuja, oravia ja satuolentoja — kannattaa katsoa ylös.",
"Kruununhaankatu": "Antaa nimen kaupunginosalle: kruununhaka oli aikoinaan kruunun hevoslaidun kaupungin laidalla.",
"Kanavakatu": "Kulkee Katajanokan kanavan suuntaisesti. Varrella vanhat satamamakasiinit, Wanha Satama ja matka jatkuu Allas Sea Poolille.",
"Kasarmikatu": "Kaartinkaupungin selkäranka ja Design Districtin pääkatu: pieniä gallerioita, muotoiluliikkeitä ja kadun päässä Kaartin kasarmi.",
"Korkeavuorenkatu": "Numerossa 23 on Designmuseo. Katu nousee Esplanadilta Ullanlinnan kallioille ja kulkee Design Districtin ytimen läpi.",
"Eteläranta": "Kauppatorin kylki: Vanha kauppahalli, torikahvit ja laiturista lähtevät Suomenlinnan lautta sekä risteilijät.",
"Pohjoinen Makasiinikatu": "Kaartinkaupungin arvokkainta kulmaa: suurlähetystöjä, muotoiluliikkeitä ja hiljaisia sisäpihoja aivan Esplanadin takana.",
"Eteläinen Makasiinikatu": "Vie Makasiinirantaan, jonka tulevaisuudesta kaupunki on kiistellyt vuosikymmeniä. Kadun päässä Olympiaterminaali ja meri.",
"Ludviginkatu": "Lyhyt katu Design Districtin sydämessä — putiikkeja, kahviloita ja Kaartinkaupungin tyypillistä empireklassista julkisivua.",
"Pieni Roobertinkatu": "Punavuoren ja Kaartinkaupungin yhdistävä pieni katu, jonka varrella baareja ja ravintoloita kivenheiton päässä Esplanadilta.",
"Tehtaankatu": "Ullanlinnan ja Eiran raja. Kadulla on Venäjän suurlähetystö, joten mielenosoitukset päätyvät tänne, ja toisessa päässä Sinebrychoffin panimoalue.",
"Merikatu": "Eiran merenpuoleinen katu: jugendhuviloita, ja kadun päästä avautuu Merisatamanranta, jonka kalliot täyttyvät kesäisin piknikeistä.",
"Laivurinkatu": "Punavuoren ja Ullanlinnan rajakatu. Jyrkkä Laivurinrinne laskee kohti merta, ja kulmilla on pieniä kahviloita ja putiikkeja.",
"Kapteeninkatu": "Ullanlinnan ja Punavuoren rajalla. Varrella Kapteeninpuistikko, pieni kolmiopuisto jossa naapurusto istuu kesäiltoina.",
"Ratakatu": "Ullanlinnan hiljainen asuinkatu. Kadun päästä nousevat Johanneksenkirkon tornit, Helsingin korkeimmat, ja kirkon portaat ovat kesällä täynnä istujia.",
"Ullanlinnankatu": "Ullanlinnan sydän: 1900-luvun alun kerrostaloja, rauhallisia pihoja ja lyhyt matka Tähtitorninvuoren huipulle.",
"Vuorimiehenkatu": "Nousee Ullanlinnan kallioille jugendtalojen välissä. Varrella Vuorimiehenpuistikko, alueen pieni naapuruspuisto.",
"Tähtitorninkatu": "Kadun yllä on Tähtitorninvuori: Engelin observatorio, näkymä satamaan ja talvella kaupungin keskeisin pulkkamäki.",
"Puistokatu": "Johtaa Kaivopuistoon, jonka huviloissa on suurlähetystöjä ja jonka Kaivohuone on toiminut kylpyläkasinosta legendaariseksi klubiksi.",
"Huvilakatu": "Eiran valokuvatuin katu: pastellinsävyisiä jugendtaloja kaaressa. Asukkaat ovat jo tottuneet kameroihin ja katukuvausryhmiin.",
"Neitsytpolku": "Kaivopuiston laidan hiljaisin osoite: suurlähetystöjen huviloita, korkeita pensasaitoja ja meri puiden takana.",
"Pietarinkatu": "Punavuoren kahvila- ja vintagekatu, jonka varrella pieniä putiikkeja ja alueen boheemi maine on syntynyt.",
"Tarkk'ampujankatu": "Ullanlinnan ylempi katu vanhan tarkk'ampujakasarmin kulmilla, aivan Johanneksenpuiston vieressä. Ainoa Helsingin kadunnimi, jossa on heittomerkki.",
"Rikhardinkatu": "Täällä on Rikhardinkadun kirjasto vuodelta 1881, Suomen ensimmäinen kirjastoksi rakennettu talo — nykyään myös Design Districtin kulmakivi.",
"Ullankatu": "Tähtitorninvuoren kylki: Ursan tähtitorni pitää yläpuolella yleisöiltoja, ja rinne on talvella pulkkamäki.",
"Laivasillankatu": "Ullanlinnan merellisin katu: toisella puolella Kaivopuiston puut, toisella satama, laiturit ja risteilijät.",
"Bulevardi": "Engelin asemakaavan ylpeys ja Helsingin ensimmäinen puistokatu. Varrella Sinebrychoffin panimo, taidemuseo ja Koffin puisto, kaupungin klassisin piknikkenttä.",
"Uudenmaankatu": "Punavuoren ravintola- ja baarikatu, jolla ilta alkaa ja usein myös päättyy. Nimi tulee Uudenmaan maakunnasta.",
"Iso Roobertinkatu": "Tuttu \"Ropa\". Se muutettiin kävelykaduksi 1980-luvulla yhtenä Suomen ensimmäisistä.",
"Fredrikinkatu": "Pitkä katu, joka vie Hietalahdesta Kampin läpi Etu-Töölöön. Hyvä mittatikku sille, kuinka pitkälle jalat kantavat.",
"Albertinkatu": "Punavuoren rauhallinen pitkittäiskatu, jonka 1900-luvun alun kerrostalot ovat täynnä korkeita ikkunoita ja kaakeliuuneja.",
"Annankatu": "Numerossa 30 on Annantalo, vanhassa koulussa toimiva lasten ja nuorten taidekeskus — myös aikuisten suosikkinäyttelypaikka.",
"Yrjönkatu": "Yrjönkadun uimahalli vuodelta 1928 on Suomen vanhin. Perinne on uida ilman uimapukua, ja naisille ja miehille on omat vuorot.",
"Kalevankatu": "Kalevalan mukaan nimetty katu, joka halkoo Kamppia ja Punavuorta. Varrella kaupungin tiheintä kahvila- ja putiikkiverkostoa.",
"Eerikinkatu": "Ruotsiksi Eriksgatan, kuten keskiaikaisten kuninkaiden kuulu valtakunnan kiertomatka.",
"Lönnrotinkatu": "Elias Lönnrotin mukaan. Kadun päässä on Vanha kirkkopuisto, jota kutsutaan Ruttopuistoksi: sinne haudattiin 1710 ruttoon kuolleita.",
"Punavuorenkatu": "Antaa nimen kaupunginosalle — Punavuori tulee alueen punertavasta kalliosta, joka näkyy yhä pihojen perällä.",
"Pursimiehenkatu": "Punavuoren poikkikatu, jonka varrella on alueen tyypillisiä 1900-luvun alun taloja ja pieniä ravintoloita.",
"Merimiehenkatu": "Punavuoren pitkä poikkikatu ja kaupunginosan boheemin maineen keskus: kahviloita, putiikkeja ja tiivistä katuelämää.",
"Malminkatu": "Kampin länsilaita. Lähistöllä on Maria 01, vanhassa sairaalassa toimiva startup-kampus, ja sen kahvila on avoin kaikille.",
"Salomonkatu": "Kampin keskuksen ja Narinkkatorin kylkeä kulkeva katu — kaupungin vilkkain vaihtopaikka bussista metroon.",
"Hietalahdenranta": "Täällä on Hietalahden kirpputori, Helsingin tunnetuin, ja kauppahalli, joka on nykyään täynnä ravintoloita.",
"Lapinlahdenkatu": "Johtaa Lapinlahteen, jossa vanha mielisairaala toimii nyt kulttuuri- ja hyvinvointikeskuksena: kahvila, sauna ja meri vieressä.",
"Runeberginkatu": "Kansallisrunoilija J. L. Runebergin mukaan — sama mies, jonka nimeä kantaa myös helmikuun torttu.",
"Arkadiankatu": "Nimi juontaa vanhasta Arkadia-teatterista. Kadun päässä on Eduskuntatalo ja sen 1930-luvun pylväikkö.",
"Museokatu": "Nimi tulee Kansallismuseosta, jonka torni kohoaa kadun itäpäässä. Museon eteinen on Gallen-Kallelan freskojen peitossa.",
"Töölönkatu": "Töölö tulee kartanon nimestä Thölö. Katu vie Etu-Töölön 1920-luvun klassisismin läpi kohti Töölön torin markkinoita.",
"Mechelininkatu": "Nimetty valtiomies Leo Mechelinin mukaan. Yksi kaupungin vilkkaimmista väylistä, mutta pyörätie sen vierellä on paikallisten valtatie.",
"Nervanderinkatu": "Nimetty tiedemiessuvun Nervanderin mukaan. Kadun kulmalta löytyy Töölön hiljaisimpia pihoja.",
"Apollonkatu": "Antiikin Apollon mukaan — Etu-Töölössä on kokonainen sarja mytologisia kadunnimiä samalla korttelialueella.",
"Aurorankatu": "Nimetty aamuruskon jumalattaren mukaan. Lähistöllä on myös vanha Aurora-sairaala samasta nimestä.",
"Dagmarinkatu": "Nimi tulee keisarinna Maria Fjodorovnasta, joka syntyi Tanskassa nimellä Dagmar.",
"Cygnaeuksenkatu": "Uno Cygnaeuksen mukaan — hän tunnetaan Suomen kansakoulun isänä, joten kiitos hänelle koko koululaitoksesta.",
"Eteläinen Hesperiankatu": "Nimi tulee antiikin Hesperiasta, \"lännen maasta\". Kadun kylkeen avautuu Hesperianpuisto ja reitti Töölönlahdelle.",
"Pohjoinen Hesperiankatu": "Hesperianpuiston pohjoislaita. Täältä pääsee kesäiltana suoraan Töölönlahden kierrokselle, joka on kaupungin klassisin lenkki.",
"Temppelikatu": "Kadun varrella on Temppeliaukion kirkko, joka on louhittu suoraan kallioon 1969. Sisällä on niin hyvä akustiikka, että konsertteja riittää ympäri vuoden.",
"Sandelsinkatu": "Nimetty kenraali J. A. Sandelsin mukaan. Vanhassa koulussa toimii Sandelsin kulttuurikeskus, jossa on kirjasto ja konsertteja.",
"Topeliuksenkatu": "Zachris Topeliuksen mukaan: sadunkertoja, sanomalehtimies ja historian professori samassa nimessä.",
"Caloniuksenkatu": "Nimetty oikeusoppineen Matthias Calonuksen mukaan. Katu laskee Töölön länsilaidalta kohti Hesperian rantaa.",
"Pohjoinen Rautatiekatu": "Kulkee ratapihan länsipuolta. Kadun varrelta näkee junien lähtevän — hyvä paikka huomata, kuinka lähellä keskustaa raiteet ovat.",
"Eteläinen Rautatiekatu": "Radan ja Kampin välissä. Kadun päässä nousee Eduskuntatalon rinne, ja alla kulkee Baanan pyöräväylä vanhassa ratakuilussa."
};
